urls.py
from django.urls import path

from . import views


app_name = "questionnaire"
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('question/<int:pk>/', views.QuestionView.as_view(), name="question_detail"),
    path('solution/<int:pk>/', views.SolutionView.as_view(), name="solution_detail"),
    path('transition/<int:pk>/solution_and_next_question', views.SolutionAndNextQuestionView.as_view(), name="solution_and_next_question"),
]

models.py
from django.db import models


CONTENT_MAX_LENGTH = 1 << 20


class Question(models.Model):
    content = models.TextField(max_length=CONTENT_MAX_LENGTH)

    def __str__(self):
        return self.content


class Answer(models.Model):
    content = models.TextField(max_length=CONTENT_MAX_LENGTH)

    def __str__(self):
        return self.content


class Solution(models.Model):
    content = models.TextField(max_length=CONTENT_MAX_LENGTH)

    def __str__(self):
        return self.content


class Transition(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    next_question = models.ForeignKey(Question,
                                      blank=True, null=True,
                                      on_delete=models.SET_NULL,
                                      related_name="incoming_transition_set")
    solution = models.ForeignKey(Solution, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        unique_together = ("question", "answer")


class Questionnaire(models.Model):
    name = models.CharField(max_length=256)
    first_question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

views.py
from django.views import generic

from .models import Question, Questionnaire, Solution, Transition


class IndexView(generic.ListView):
    model = Questionnaire
    template_name = "questionnaire/index.html"


class DetailView(generic.DetailView):
    model = Questionnaire
    template_name = "questionnaire/detail.html"


class QuestionView(generic.DetailView):
    model = Question
    template_name = "questionnaire/question.html"


class SolutionView(generic.DetailView):
    model = Solution
    template_name = "questionnaire/solution.html"


class SolutionAndNextQuestionView(generic.DetailView):
    model = Transition
    template_name = "questionnaire/solution_and_next_question.html"

templates/questionnaire/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'questionnaire/css/content.css' %}"/>
</head>
<body>
    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/questionnaire/detail.html
{% extends "questionnaire/base.html" %}

{% block title %}{{ questionnaire.name }}{% endblock %}

{% block content %}
    <h3>{{ questionnaire.name }}</h3>

    <div id="questionnaire">
        {% include "questionnaire/question.html" with question=questionnaire.first_question%}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script type="text/javascript">
        function customize_radio_btns(context){
            $(":radio[name^='transition']", context).click(function() {
                const btn = $(this);
                btn.closest("div.question").nextAll().remove();

                const url = "{% url 'questionnaire:solution_and_next_question' 222 %}".replace("222", $(this).val().toString()); // TODO: FIX THIS SHIT

                $.get(url, function(data){
                    $("div#questionnaire").append(data);
                    customize_radio_btns(btn.closest("div.question").nextAll());
                });
            });
        }

        $(function(){
            customize_radio_btns('');
        });
    </script>

{% endblock %}

templates/questionnaire/index.html
{% extends "questionnaire/base.html" %}

{% block title %}Questionnaires{% endblock %}

{% block content %}
    <h3>Questionnaires</h3>

    {% if questionnaire_list %}
        <ul>
            {% for questionnaire in questionnaire_list %}
                <li><a href="{% url "questionnaire:detail" questionnaire.id %}">
                    {{ questionnaire.name }}
                </a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No questionnaires are available.</p>
    {% endif %}
{% endblock %}

templates/questionnaire/question.html
<div class="question">
    <p class="question-content">{{ question.content }}</p>
    {% for transition in question.transition_set.all %}
        <p class="answer">
            <input type="radio" name="transition-{{ question.id }}"
                   id="transition-{{ question.id }}-{{ forloop.counter }}"
                   value="{{ transition.id }}"/>
            <label for="transition-{{ question.id }}-{{ forloop.counter }}">{{ transition.answer.content }}</label>
        </p>
    {% endfor %}
</div>

templates/questionnaire/solution.html
<p>{{ solution.content }}</p>

templates/questionnaire/solution_and_next_question.html
{% include "questionnaire/solution.html" with solution=transition.solution%}
{% include "questionnaire/question.html" with question=transition.next_question%}